# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swrunesadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runa',
            name='pos',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, null=True, verbose_name='Posição'),
        ),
        migrations.AlterField(
            model_name='runa',
            name='typerune',
            field=models.CharField(blank=True, choices=[('despair', 'Despair'), ('revenge', 'Revenge')], max_length=20, null=True, verbose_name='Tipo'),
        ),
    ]
