# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('swrunesadmin', '0002_auto_20180725_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atributoruna',
            name='cmsplugin_ptr',
        ),
        migrations.AddField(
            model_name='runa',
            name='fifthatr',
            field=models.CharField(blank=True, choices=[('atk', 'Atk'), ('hp', 'Hp'), ('def', 'Def'), ('spd', 'Spd'), ('dan', 'Dan'), ('tax', 'Tax'), ('res', 'Res'), ('pre', 'Pre')], max_length=5, null=True, verbose_name='Sub-atributo 3'),
        ),
        migrations.AddField(
            model_name='runa',
            name='firstatr',
            field=models.CharField(blank=True, choices=[('atk', 'Atk'), ('hp', 'Hp'), ('def', 'Def'), ('spd', 'Spd'), ('dan', 'Dan'), ('tax', 'Tax'), ('res', 'Res'), ('pre', 'Pre')], max_length=5, null=True, verbose_name='Atributo principal'),
        ),
        migrations.AddField(
            model_name='runa',
            name='fourthatr',
            field=models.CharField(blank=True, choices=[('atk', 'Atk'), ('hp', 'Hp'), ('def', 'Def'), ('spd', 'Spd'), ('dan', 'Dan'), ('tax', 'Tax'), ('res', 'Res'), ('pre', 'Pre')], max_length=5, null=True, verbose_name='Sub-atributo 2'),
        ),
        migrations.AddField(
            model_name='runa',
            name='secondatr',
            field=models.CharField(blank=True, choices=[('atk', 'Atk'), ('hp', 'Hp'), ('def', 'Def'), ('spd', 'Spd'), ('dan', 'Dan'), ('tax', 'Tax'), ('res', 'Res'), ('pre', 'Pre')], max_length=5, null=True, verbose_name='Atributo secundário'),
        ),
        migrations.AddField(
            model_name='runa',
            name='sixthatr',
            field=models.CharField(blank=True, choices=[('atk', 'Atk'), ('hp', 'Hp'), ('def', 'Def'), ('spd', 'Spd'), ('dan', 'Dan'), ('tax', 'Tax'), ('res', 'Res'), ('pre', 'Pre')], max_length=5, null=True, verbose_name='Sub-atributo 4'),
        ),
        migrations.AddField(
            model_name='runa',
            name='thirdatr',
            field=models.CharField(blank=True, choices=[('atk', 'Atk'), ('hp', 'Hp'), ('def', 'Def'), ('spd', 'Spd'), ('dan', 'Dan'), ('tax', 'Tax'), ('res', 'Res'), ('pre', 'Pre')], max_length=5, null=True, verbose_name='Sub-atributo 1'),
        ),
        migrations.AlterField(
            model_name='runa',
            name='pos',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1, null=True, verbose_name='Posição'),
        ),
        migrations.AlterField(
            model_name='runa',
            name='typerune',
            field=models.CharField(blank=True, choices=[('despair', 'Despair'), ('revenge', 'Revenge'), ('blade', 'Blade'), ('energy', 'Energy'), ('swift', 'Swift'), ('fatal', 'Fatal'), ('will', 'Will'), ('rage', 'Rage'), ('focus', 'Focus'), ('guard', 'Guard'), ('violent', 'Volent'), ('nemesis', 'Nemesis'), ('shield', 'Shield'), ('destroy', 'Destroy'), ('endure', 'Endure'), ('vampire', 'vampire'), ('fight', 'Fight'), ('determination', 'Determination'), ('enhanced', 'Enhanced'), ('accuracy', 'Accuracy'), ('tolerance', 'Tolerance')], max_length=20, null=True, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='AtributoRuna',
        ),
    ]
