# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('swrunesadmin', '0003_auto_20180725_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoRuna',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='swrunesadmin_atributoruna', serialize=False, to='cms.CMSPlugin')),
                ('atribute', models.CharField(blank=True, choices=[('atk', 'Atk'), ('hp', 'Hp'), ('def', 'Def'), ('spd', 'Spd'), ('dan', 'Dan'), ('tax', 'Tax'), ('res', 'Res'), ('pre', 'Pre')], max_length=5, null=True, verbose_name='Atributo')),
                ('active', models.BooleanField(default=True, verbose_name='Com %')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='runa',
            name='fifthatr',
        ),
        migrations.RemoveField(
            model_name='runa',
            name='firstatr',
        ),
        migrations.RemoveField(
            model_name='runa',
            name='fourthatr',
        ),
        migrations.RemoveField(
            model_name='runa',
            name='secondatr',
        ),
        migrations.RemoveField(
            model_name='runa',
            name='sixthatr',
        ),
        migrations.RemoveField(
            model_name='runa',
            name='thirdatr',
        ),
    ]
