# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swrunesadmin', '0006_auto_20180725_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributoruna',
            name='order',
            field=models.CharField(blank=True, choices=[('principal', 'Principal'), ('secundário', 'Secundário'), ('sub-atr 1', 'Sub-atr 1'), ('sub-atr 2', 'Sub-atr 2'), ('sub-atr 3', 'Sub-atr 3'), ('sub-atr 4', 'Sub-atr 4')], max_length=20, null=True, verbose_name='Ordem do atributo'),
        ),
    ]
